config/routes.rb
Rich::Engine.routes.draw do
  
  resources :files, :controller => "files"
  
end

app/models/rich/rich_file.rb
require 'cgi'
require 'mime/types'
require 'kaminari'

module Rich
  class RichFile < ActiveRecord::Base
    scope :images,  -> { where("rich_rich_files.simplified_type = 'image'") }
    scope :files,   -> { where("rich_rich_files.simplified_type = 'file'") }

    paginates_per Rich.options[:paginates_per]
  end
end

app/controllers/rich/files_controller.rb
module Rich
  class FilesController < ApplicationController

    before_filter :authenticate_rich_user
    before_filter :set_rich_file, only: [:show, :destroy]

    layout "rich/application"

    def index
      @type = params[:type]

      if(params[:scoped] == 'true')
        if(@type == "image")
          @items = RichFile.images.order("created_at DESC").where("owner_type = ? AND owner_id = ?", params[:scope_type], params[:scope_id]).page params[:page]
        else
          @items = RichFile.files.order("created_at DESC").where("owner_type = ? AND owner_id = ?", params[:scope_type], params[:scope_id]).page params[:page]
        end
      else
        if(@type == "image")
          @items = RichFile.images.order("created_at DESC").page params[:page]
        else
          @items = RichFile.files.order("created_at DESC").page params[:page]
        end
      end

      # stub for new file
      @rich_asset = RichFile.new

      respond_to do |format|
        format.html
        format.js
      end

    end

    def show
      # show is used to retrieve single files through XHR requests after a file has been uploaded

      if(params[:id])
        # list all files
        @file = @rich_file
        render :layout => false
      else
        render :text => "File not found"
      end

    end

    def create

      @file = RichFile.new(:simplified_type => params[:simplified_type])

      if(params[:scoped] == 'true')
        @file.owner_type = params[:scope_type]
        @file.owner_id = params[:scope_id].to_i
      end

      # use the file from Rack Raw Upload
      file_params = params[:file] || params[:qqfile]
      if(file_params)
        file_params.content_type = Mime::Type.lookup_by_extension(file_params.original_filename.split('.').last.to_sym)
        @file.rich_file = file_params
      end

      if @file.save
        response = { :success => true, :rich_id => @file.id }
      else
        response = { :success => false,
                     :error => "Could not upload your file:\n- "+@file.errors.to_a[-1].to_s,
                     :params => params.inspect }
      end

      render :json => response, :content_type => "text/html"
    end

    def destroy
      if(params[:id])
        @rich_file.destroy
        @fileid = params[:id]
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_rich_file
        @rich_file = RichFile.find(params[:id])
      end
  end
end

app/helpers/rich/application_helper.rb
module Rich
  module ApplicationHelper
  end
end

app/helpers/rich/files_helper.rb
module Rich
  module FilesHelper
    
    def thumb_for_file(file)
      if file.simplified_type == "image"
        file.rich_file.url(:rich_thumb)
      else
        asset_path "rich/document-thumb.png"
      end
    end
    
  end
end

app/views/layouts/rich/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rich Browser</title>
  <%= stylesheet_link_tag    "rich/application" %>
  <%= javascript_include_tag "rich/application" %>
  <%= csrf_meta_tags %>
  </head>
<body>

<%= yield %>

</body>
</html>

app/views/rich/files/_file.html.erb
<li class="clickable">
  <img  id="file<%= file.id %>"
        src="<%= thumb_for_file(file) %>" 
        data-uris="<%= file.uri_cache %>"
        data-rich-asset-id="<%= file.id %>"
				data-rich-asset-type="<%= file.simplified_type %>"
				data-rich-asset-name="<%= file.rich_file_file_name %>"
  />
  <p><%= file.rich_file_file_name %></p>
  <%= link_to "delete", "/rich/files/"+file.id.to_s, :method => :delete, :remote => true, :data => { :confirm => t(:delete_confirm) }, :class => "delete", :title => t(:delete) %>
</li>

app/views/rich/files/destroy.js.erb
$("#file<%= @fileid %>").parent().remove();

app/views/rich/files/index.html.erb
<header>
  
	<div id="loading" style="display:none;"></div>

  <div id="view-toggle">
    <a href="#" id="view-grid" title="<%= t(:view_grid_tip) %>"><%= t(:view_grid) %></a>
    <a href="#" id="view-list" title="<%= t(:view_list_tip) %>"><%= t(:view_list) %></a>
  </div>

  <div id="insert-toggle">
    <a href="#" id="insert-many" title="<%= t(:insert_many_tip) %>"><%= t(:insert_many) %></a>
    <a href="#" id="insert-one" title="<%= t(:insert_one_tip) %>"><%= t(:insert_one) %></a>  
  </div>

  <ul id="styles" class="scopes">
    <li class="label"><%= t(:available_styles) %></li>
  </ul>
  
</header>

<div id="legacy-form"><%= form_for(@rich_asset, :url => files_path) do |f| %>
  <p><%= f.file_field :rich_file%></p>
  <%= f.submit("Upload") %>
<% end %>
</div>

<ul id="items">
  
  <li id="uploadBlock">
    <div id="upload" class="qq-upload-button placeholder">
      <div class="spinner"></div>
    </div>
    <p><%= t(:upload_a_file) %></p>
  </li>

	<%= render :partial => "file", :collection => @items, :as => :file %>

</ul>

app/views/rich/files/index.js.erb
<% if @items.count > 0 %>$("#items").append("<%= escape_javascript(render :partial => "file", :collection => @items, :as => :file) %>");<% end %>

app/views/rich/files/show.html.erb
<%= render :partial => 'file', :locals => {:file => @file} %>